### ISSUE TITLE
Add missing Armor parts to JEI tab for materials with no tool parts

### ISSUE THREAD

**Issue by ffuentesm** [paypur/TConJEI#2]
I know the mod just ported to 1.19.2 and has yet to implement the new changes to the JEI tab.
I am just mentioning the current problem for materials with only armor parts. 
![image](https://github.com/paypur/TConJEI/assets/44974827/9f3c4258-2506-4e15-b948-99751846a4ee)![image](https://github.com/paypur/TConJEI/assets/44974827/bf7cfd43-d78f-4b7c-953e-1369ddf708c4)

**Comment by paypur** [comment]
My plan for the next release is to split the stat pages into harvest, ranged, and armor categories. Because the way I currently handle drawing the stats, I have to explicitly say that this materials has these categories which is why are is blank for now.

**Comment by ffuentesm** [comment]
Thanks, also, would be possible to add a tab for the spitting fluid effects? 
Here is the list: https://docs.google.com/spreadsheets/d/19Nbi-jTrhZg4zMZ8DreELWHv6SZDik5wxiz13Iqhnbw/htmlview

**Comment by paypur** [comment]
I'll look into later. I'm just not really sure how I would do that programmatically.

**Comment by paypur** [comment]
Implemented in release 1.2.0
